name: "Sample React CI PipeLine / Workflow"


on: 
    push: 
        branches:
             - main
             - master
jobs: 
    build-and-test:
        runs-on: "ubuntu-latest"
    
        steps:
            - name: "Setup Node Js"
              uses: actions/setup-node@v4
              with:
                node-version: "22"
                
            - name: "Node Version Check"
              uses: node --version

            - name: "Clone the Repository"
              uses: actions/checkout@v4

            - name: "Install Dependencies"
              uses: npm install

            - name: "list Directories"
              uses: ls
